"""The Alembic migration history.

The migrations are the only thing that builds the production schema, so they
are worth testing directly: that they build the whole schema from empty, that
they tear it back down, and that they have not drifted from the models.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

from tests.conftest import SERVER_ROOT, downgrade_migrations, run_migrations

EXPECTED_TABLES = {
    "substrands",
    "teachers",
    "content_units",
    "teaching_sessions",
    "questions",
    "tests",
}


def table_names(database_url: str) -> set[str]:
    engine = create_engine(database_url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_builds_the_whole_schema_from_empty(database_url: str):
    run_migrations(database_url)

    assert EXPECTED_TABLES <= table_names(database_url)


def test_downgrade_removes_every_table_it_created(database_url: str):
    run_migrations(database_url)

    downgrade_migrations(database_url)

    assert table_names(database_url) & EXPECTED_TABLES == set()


def test_schema_round_trips_through_downgrade_and_upgrade(database_url: str):
    run_migrations(database_url)
    before = table_names(database_url)

    downgrade_migrations(database_url)
    run_migrations(database_url)

    assert table_names(database_url) == before


def test_migrations_have_not_drifted_from_the_models(migrated_database_url: str):
    """Fails when a model changes without a matching migration, which would
    otherwise only surface as a production error."""
    config = Config(str(SERVER_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(SERVER_ROOT / "migrations"))
    config.set_main_option("sqlalchemy.url", migrated_database_url)

    try:
        command.check(config)
    except AutogenerateDiffsDetected as detected:
        pytest.fail(f"models and migrations disagree: {detected}")
